Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.1.10"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "2"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    wget https://apt.puppetlabs.com/puppet6-release-bionic.deb
    dpkg -i puppet6-release-bionic.deb
    apt-get update
    apt-get install puppet-agent -y
  SHELL
end
