BOX_IMAGE = "bento/ubuntu-20.04"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "master"
    subconfig.vm.network :private_network, ip: "10.0.0.10"
    subconfig.vm.provision "shell", inline: <<-SHELL
      wget https://apt.puppet.com/puppet8-release-focal.deb
      sudo dpkg -i puppet8-release-focal.deb
      apt-get update -y
      apt-get install -y puppetserver
      ln -s /opt/puppetlabs/bin/puppet /usr/bin/puppet
    SHELL
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
      subconfig.vm.provision "shell", inline: <<-SHELL
        wget https://apt.puppet.com/puppet8-release-focal.deb
        sudo dpkg -i puppet8-release-focal.deb
        apt-get update -y
        apt-get install -y puppet-agent
        ln -s /opt/puppetlabs/bin/puppet /usr/bin/puppet
      SHELL
    end
  end
end